frontend:
  image: gitlab.praktikum-services.ru:5050/std-028-65/sausage-store/sausage-frontend
  tag: latest
  pullPolicy: Always

replicaCount: 1
ingress:
  enabled: true
  host: "afanasev-evgeniy-28.k8s.praktikum-services.tech"
backend:
  host: store-backend
  port: "8080"
service:
  type: ClusterIP
  port: 80

imagePullSecrets: 
  name: docker-config-secret