---
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  labels:
    app: db-credentials
data:
  SPRING_DATASOURCE_PASSWORD: VGVzdHVzcjEyMzQ=
  SPRING_DATASOURCE_USERNAME: c3RkLTAyOC02NQ==
  SPRING_DATA_MONGODB_URI: bW9uZ29kYjovL3N0ZC0wMjgtNjU6VGVzdHVzcjEyMzRAcmMxYS1nY2s5MGN3cW1pM2xzM3k1Lm1kYi55YW5kZXhjbG91ZC5uZXQ6MjcwMTgvc3RkLTAyOC02NT90bHM9dHJ1ZQ==
  REPORTS_MONGODB_URI: bW9uZ29kYjovL3N0ZC0wMjgtNjU6VGVzdHVzcjEyMzRAcmMxYS1nY2s5MGN3cW1pM2xzM3k1Lm1kYi55YW5kZXhjbG91ZC5uZXQ6MjcwMTgvc3RkLTAyOC02NT90bHM9dHJ1ZSZ0bHNBbGxvd0ludmFsaWRDZXJ0aWZpY2F0ZXM9dHJ1ZQ==
type: Opaque

# Секрет, необходимый, чтобы взаимодействовать с Docker Registry в GitLab:
---
apiVersion: v1
data:
  .dockerconfigjson: ew0KICAgICJhdXRocyI6IHsNCiAgICAgICAgImdpdGxhYi5wcmFrdGlrdW0tc2VydmljZXMucnU6NTA1MCI6IHsNCiAgICAgICAgICAgICJhdXRoIjogImMzUmtMVEF5T0MwMk5UcDVTM00xYTFsR1RFc3lWRmw1VVVwamJrNVJOdz09Ig0KICAgICAgICB9DQogICAgfQ0KfSA=
kind: Secret
metadata:
  name: docker-config-secret
  namespace: std-028-65
type: kubernetes.io/dockerconfigjson
