variables:
   VERSION: 1.0.${CI_PIPELINE_ID}

stages:
   - deploy

deploy-k8s:
  stage: deploy
  image: alpine/k8s:1.22.6
  script:
    - export KUBECONFIG=$KUBE_CONFIG
    - kubectl apply -f ./kubernetes/backend
    - kubectl apply -f ./kubernetes/backend-report
    - kubectl apply -f ./kubernetes/frontend

  environment:
    name: afanasev-evgeniy-28.k8s.praktikum-services.tech
    url: https://afanasev-evgeniy-28.k8s.praktikum-services.tech